source 'https://github.com/CocoaPods/Specs.git'

target 'GooglePlacesDemos' do
    platform :ios, '14.0'
    pod 'GooglePlaces', '= 8.1.0'
    project './GooglePlacesDemos.xcodeproj'
    workspace './GooglePlacesDemos.xcworkspace'
end
