source 'https://github.com/CocoaPods/Specs.git'

target 'GooglePlacesSwiftXCFrameworkDemos' do
  project 'GooglePlacesSwiftXCFrameworkDemos'
    platform :ios, '15.0'
    pod 'GooglePlaces', '= 9.0.0'
end
