source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

target 'GooglePlacesSwiftXCFrameworkDemos' do
    project 'GooglePlacesSwiftXCFrameworkDemos'
    pod 'GooglePlaces', '= 9.1.0'
end
