source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

target 'GoogleNavSwiftXCFrameworkDemos' do
    project 'GoogleNavSwiftXCFrameworkDemos'
    pod 'GoogleNavigation', '= 9.1.0'
end
