source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '15.0'

target 'GoogleMapsXCFrameworkDemos' do
  project 'GoogleMapsXCFrameworkDemos'
    platform :ios, '15.0'
    pod 'GoogleMaps', '= 9.0.0'
end
