source 'https://github.com/CocoaPods/Specs.git'
target 'MapsAndPlacesDemo' do
  use_frameworks!
  pod 'GoogleMaps', '~>4.0.0'
  pod 'GooglePlaces', '~>4.0.0'
  pod 'Google-Maps-iOS-Utils', '~> 3.1.4'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/ActionSheet'
  pod 'MaterialComponents/Banner'
  pod 'MaterialComponents/Cards'
  pod 'MaterialComponents/Snackbar'
end
