source 'https://cdn.cocoapods.org/'

platform :ios, '16.0'

target 'MapsAndPlacesDemo' do
  use_frameworks!
  pod 'GoogleMaps', '~>10.0.0'
  pod 'GooglePlaces', '~>10.0.0'
  pod 'Google-Maps-iOS-Utils', '~> 3.1.4'
  pod 'MaterialComponents/Buttons'
  pod 'MaterialComponents/AppBar'
  pod 'MaterialComponents/ActionSheet'
  pod 'MaterialComponents/Banner'
  pod 'MaterialComponents/Cards'
  pod 'MaterialComponents/Snackbar'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end